/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_CmdlineScreen
#define HEADER_CmdlineScreen
#include <sys/types.h>


#include "ProcessList.h"
#include "Panel.h"
#include "FunctionBar.h"

typedef struct CmdlineScreen_ {
   Process* process;
   Panel* display;
   FunctionBar* bar;
} CmdlineScreen;

CmdlineScreen* CmdlineScreen_new(Process* process);

void CmdlineScreen_delete(CmdlineScreen* this);

void CmdlineScreen_run(CmdlineScreen* this);

#endif
