/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_util
#define HEADER_util
/* util.c */

#include <stdio.h>
#include <stdarg.h>
#include <stdlib.h>

void
die( const char *msg, ... );

void
noerr( int rc );

/* vim:ts=2:sw=2:sts=2:et:ft=c 
 */

#endif
