/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_util
#define HEADER_util
/* util.c */

#include <stdio.h>
#include <stdlib.h>
#include <mach/kern_return.h>

void
noerr( kern_return_t rc );

/* vim:ts=2:sw=2:sts=2:et:ft=c 
 */

#endif
